CREATE TABLE ADMIN (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ADMIN_EURIBOR_DATE VARCHAR(30) NOT NULL,
    ADMIN_EURIBOR_RATE NUMERIC(100,30) NOT NULL,
    ADMIN_BANK_MARGIN NUMERIC(100,30) NOT NULL,
    ADMIN_CONTRACT_FEE NUMERIC(100,30) NOT NULL,
    ADMIN_REGISTRATION_FEE NUMERIC(100,30) NOT NULL,
    ADMIN_MONTHLY_BANK_FEE NUMERIC(100,30) NOT NULL,
    ADMIN_MIN_PROPERTY_PRICE NUMERIC(100,30) NOT NULL,
    ADMIN_MAX_PROPERTY_PRICE NUMERIC(100,30) NOT NULL,
    ADMIN_DEFAULT_PROPERTY_PRICE NUMERIC(100,30) NOT NULL,
    ADMIN_MIN_DEPOSIT_PERCENT NUMERIC(100,30) NOT NULL
     );


INSERT INTO ADMIN (ID, ADMIN_EURIBOR_DATE, ADMIN_EURIBOR_RATE, ADMIN_BANK_MARGIN, ADMIN_CONTRACT_FEE, ADMIN_REGISTRATION_FEE,
                    ADMIN_MONTHLY_BANK_FEE, ADMIN_MIN_PROPERTY_PRICE, ADMIN_MAX_PROPERTY_PRICE, ADMIN_DEFAULT_PROPERTY_PRICE, ADMIN_MIN_DEPOSIT_PERCENT)
                    VALUES (1,'2023-03-31', 3.31, 1.99, 500, 10, 50, 20000, 800000, 50000, 15);
